### ISSUE TITLE
error when importing module on windows

### ISSUE THREAD

**Issue by w00zla** [Koromix/luigi#12]
I get an error just when importing the module: 
![image](https://user-images.githubusercontent.com/5623214/178489803-4763ae69-f681-464d-9536-4a97690359e8.png)

Translation: "**a DLL initialization routine has failed**"

_ENV:_

Win10
Electron v19.0.6
Node v16.14.2
koffi v1.3.8

**Comment by Koromix** [comment]
Thanks for the report, the Windows x64 build was indeed not compatible with Electron. This should be fixed in 1.3.9 :)
