### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by aw1875** [Koromix/luigi#15]
For some reason I am unable to install the newest few versions. I'm given this error message:

```
error koffi@1.3.11: The engine "napi" is incompatible with this module. Expected version 8. Got "8"
```

Anything above version 1.3.5 gives me the same error.

Running Node v16.16.0
NPM v8.15.0
Yarn v1.22.19

Edit: It seems to be a yarn issue only, I was able to install it no problems with NPM which is odd.

**Comment by aw1875** [comment]
Version 1.3.5 does work great for the dll I wrote though so wanted to say thank you for you work!

**Comment by Koromix** [comment]
Thanks for the report, I had never used yarn before.

I've released Koffi 1.3.12 which is compatible with yarn 1.x and 3.x.

**Comment by aw1875** [comment]
Also a side note, I noticed you recently made updates to work with electron so wanted to shoot this question out in case you know the solution. When I work with a template such as [this one](https://github.com/karolis-sh/electron-snowpack) I get the same issue that was described in another issue (#12 ). Any idea why this might be?

**Comment by Koromix** [comment]
This still happens even with version 1.3.12?

**Comment by aw1875** [comment]
Only with templates like the one linked (it may just be the way that one bundles). If I create a fresh electron project it works perfectly.

**Comment by Koromix** [comment]
OK, I'll look into it :)

**Comment by aw1875** [comment]
Appreciate it and appreciate the work you're doing!

**Comment by Koromix** [comment]
Thanks!

Could you point me to a preconfigured repository based on electron-snowpack though? Honestly, the README "Getting started" section really does not start much and I have very little patience for this kind of thing... 😅

**Comment by aw1875** [comment]
Ya its a little confusing honestly, maybe [this example](https://github.com/karolis-sh/electron-snowpack/tree/main/examples/react-typescript) will be helpful. If not let me know and I'll try to find something more helpful!
