### ISSUE TITLE
koffi: Ordinal Function [Question / Feature request]

### ISSUE THREAD

**Issue by xan105** [Koromix/luigi#2]
On Windows, some exported dll functions can't be accessed by name but only by ordinal (_address_).
Which I don't think node-ffi / node-ffi-napi can do.
I only found it mentioned in `node-ffi#398` without answers.

_eg: `XInputGetCapabilitiesEx` from the `xinput1_4.dll` can only be accessed by its ordinal: 108_
Using by name XInputGetCapabilitiesEx or ordinal 108 and `node-ffi-napi` just crashes.

<details><summary>C++ quick and dirty demo to access it</summary>

```cpp
#include <Windows.h>
#include <Xinput.h>
#pragma comment(lib, "xinput.lib")

struct XINPUT_CAPABILITIES_EX
{
	XINPUT_CAPABILITIES Capabilities;
	WORD VendorId;
	WORD ProductId;
	WORD VersionNumber;
	DWORD unk1;
};
typedef DWORD(_stdcall* _XInputGetCapabilitiesEx)(DWORD unk1, DWORD dwUserIndex, DWORD dwFlags, XINPUT_CAPABILITIES_EX* pCapabilities);

_XInputGetCapabilitiesEx XInputGetCapabilitiesEx = (_XInputGetCapabilitiesEx)GetProcAddress(GetModuleHandleW(L"XInput1_4.dll"), (LPCSTR)108);
```

</details> 

Do you think this is something possible to do / add in koffi ?
I'm not knowledgeable enough to know if this apply also to other platforms such as Linux.

I'm asking because I found out about this lib on reddit and benchmark seems promising.
Since it's still in its infancy, I thought I'd ask.

**Comment by Koromix** [comment]
Good idea!

This is Windows-specific, AFAIK nothing like this exists on Linux or macOS. I've added support for ordinal numbers in the latest commit. So numbers are only allowed on Windows.

This example seems to work even though the call fails because I have no controller, with error 1167 (ERROR_DEVICE_NOT_CONNECTED):

```js
const koffi = require('./build/koffi.node');
const lib = koffi.load('xinput1_4.dll');

const XINPUT_GAMEPAD = koffi.struct('XINPUT_GAMEPAD', {
    buttons: 'uint16_t',
    left_trigger: 'uint8_t',
    right_trigger: 'uint8_t',
    thumb_lx: 'uint16_t',
    thumb_ly: 'uint16_t',
    thumb_rx: 'uint16_t',
    thumb_ry: 'uint16_t'
});

const XINPUT_VIBRATION = koffi.struct('XINPUT_VIBRATION', {
    left_motor_speed: 'uint16_t',
    right_motor_speed: 'uint16_t'
});

const XINPUT_CAPABILITIES = koffi.struct('XINPUT_CAPABILITIES', {
    type: 'uint8_t',
    subtype: 'uint8_t',
    flags: 'uint16_t',
    gamepad: XINPUT_GAMEPAD,
    vibration: XINPUT_VIBRATION
});

const XINPUT_CAPABILITIES_EX = koffi.struct('XINPUT_CAPABILITIES_EX', {
    capabilities: XINPUT_CAPABILITIES,
    vendor_id: 'uint16_t',
    product_id: 'uint16_t',
    version_number: 'uint16_t',
    unk1: 'uint32_t'
});

const XInputGetCapabilitiesEx = lib.stdcall(108, 'uint32_t', ['uint32_t', 'uint32_t', 'uint32_t', koffi.out(koffi.pointer(XINPUT_CAPABILITIES_EX))]);

let caps = {};
let ret = XInputGetCapabilitiesEx(1, 0, 0, caps);
console.log(ret, caps);
```

**Comment by Koromix** [comment]
I've made a release with this change, version 0.9.35 :)

**Comment by xan105** [comment]
Works perfectly !

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/14090532/167166262-116a1ada-77b8-486a-beb3-3bb109ad7b19.png)

</details>

Thank you for your prompt answer and implementation :)
That's why I love open source 😉
Thanks for your time, closing.

**Comment by xan105** [comment]
There is a regression starting with 0.9.36 onward.

Calling a function by ordinal simply crash.

<details><summary>Stack dump (0.9.48)</summary>

<pre>
FATAL ERROR: Error::New napi_get_last_error_info
 1: 00007FF62C477A1F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114207
 2: 00007FF62C406096 DSA_meth_get_flags+65542
 3: 00007FF62C406F4D node::OnFatalError+301
 4: 00007FF62C406749 DSA_meth_get_flags+67257
 5: 00007FF62C4357AC napi_fatal_error+156
 6: 00007FF9C6775E56
 7: 00007FF9C677634A
 8: 00007FF9C677DF34
 9: 00007FF9C6781921
10: 00007FF62C4442EB node::Stop+36395
11: 00007FF62CCF5CA6 v8::internal::Builtins::code_handle+172790
12: 00007FF62CCF5899 v8::internal::Builtins::code_handle+171753
13: 00007FF62CCF5B5C v8::internal::Builtins::code_handle+172460
14: 00007FF62CCF59C0 v8::internal::Builtins::code_handle+172048
15: 00007FF62CDC90C1 v8::internal::SetupIsolateDelegate::SetupHeap+494673
16: 00007FF62CD5B56E v8::internal::SetupIsolateDelegate::SetupHeap+45310
17: 00007FF62CD5B56E v8::internal::SetupIsolateDelegate::SetupHeap+45310
18: 00007FF62CD8D3F4 v8::internal::SetupIsolateDelegate::SetupHeap+249732
19: 00007FF62CD5977C v8::internal::SetupIsolateDelegate::SetupHeap+37644
20: 00007FF62CD5937B v8::internal::SetupIsolateDelegate::SetupHeap+36619
21: 00007FF62CC39E91 v8::internal::Execution::CallWasm+1521
22: 00007FF62CC39FDB v8::internal::Execution::CallWasm+1851
23: 00007FF62CC3A9E5 v8::internal::Execution::TryCall+213
24: 00007FF62C9E5222 v8::internal::SerializeStackFrameInfo+10242
25: 00007FF62C9E7530 v8::internal::SourceTextModule::GetImportMeta+2512
26: 00007FF62C9E4BC9 v8::internal::SerializeStackFrameInfo+8617
27: 00007FF62CA20EF7 v8::internal::JSPromise::status+3367
28: 00007FF62CA20C1C v8::internal::JSPromise::status+2636
29: 00007FF62CD24EAE v8::Module::Evaluate+526
30: 00007FF62C43D598 node::Stop+8408
31: 00007FF62CCF5CA6 v8::internal::Builtins::code_handle+172790
32: 00007FF62CCF5899 v8::internal::Builtins::code_handle+171753
33: 00007FF62CCF5B5C v8::internal::Builtins::code_handle+172460
34: 00007FF62CCF59C0 v8::internal::Builtins::code_handle+172048
35: 00007FF62CDC90C1 v8::internal::SetupIsolateDelegate::SetupHeap+494673
36: 00007FF62CD5B56E v8::internal::SetupIsolateDelegate::SetupHeap+45310
37: 00007FF62CD8B243 v8::internal::SetupIsolateDelegate::SetupHeap+241107
38: 00007FF62CE11852 v8::internal::SetupIsolateDelegate::SetupHeap+791522
39: 00007FF62CD7D47A v8::internal::SetupIsolateDelegate::SetupHeap+184330
40: 00007FF62CD5967B v8::internal::SetupIsolateDelegate::SetupHeap+37387
41: 00007FF62CC39EBB v8::internal::Execution::CallWasm+1563
42: 00007FF62CC39FDB v8::internal::Execution::CallWasm+1851
43: 00007FF62CC3AA8A v8::internal::Execution::TryCall+378
44: 00007FF62CC16E1A v8::internal::MicrotaskQueue::RunMicrotasks+410
45: 00007FF62CC16BBA v8::internal::MicrotaskQueue::PerformCheckpointInternal+74
46: 00007FF62C4A60E2 node::CallbackScope::~CallbackScope+978
47: 00007FF62C4A5D7E node::CallbackScope::~CallbackScope+110
48: 00007FF62C39797C std::basic_ostream<char,std::char_traits<char> >::operator<<+80092
49: 00007FF62C396186 std::basic_ostream<char,std::char_traits<char> >::operator<<+73958
50: 00007FF62C395E45 std::basic_ostream<char,std::char_traits<char> >::operator<<+73125
51: 00007FF62C4A56E0 node::SpinEventLoop+336
52: 00007FF62C3BE853 v8::internal::Isolate::stack_guard+53843
53: 00007FF62C43AADC node::Start+220
54: 00007FF62C25897C RC4_options+348284
55: 00007FF62D2BFE98 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+14472
56: 00007FF9E6427034 BaseThreadInitThunk+20
57: 00007FF9E6EC2651 RtlUserThreadStart+33
</pre>

</details>

Calling by name is fine.
I'm importing your lib with esm `import` _if it matters._

You can reuse [your code snippet from above](https://github.com/Koromix/luigi/issues/2#issuecomment-1119582214) to trigger the crash.

**Comment by Koromix** [comment]
Indeed, sorry about that...
It should work correctly in version 1.0.1. And this time I've added a test to avoid a new regression in the future.

**Comment by xan105** [comment]
Confirm it's working again with 1.0.1.
Thanks for the quick fix.
