### ISSUE TITLE
koffi: async library calls [Question]

### ISSUE THREAD

**Issue by xan105** [Koromix/luigi#4]
Are koffi calls synchronous and do they block the event loop like ffi / ffi-napi ?
ffi / ffi-napi has an `.async()` method returned for any FFI'd function (using libuv).
cf: https://github.com/node-ffi/node-ffi/wiki/Node-FFI-Tutorial#async-library-calls

This is something I often use to provide sync / promise version of my exported api.
Granted I _only really_ needed it in two cases where I was spamming invocation calls and not blocking the event loop was necessary:
 - In an Electron project calling a steam friend network scan every 3sec
 - Again spamming calls to get XInput buttons pressed down every `window.requestAnimationFrame();` (so **very** often) or in a one sec loop

🤔 If this is not too much of a hassle, might be something worth to look at ?
I don't know what kind of black magic is koffi using under the hood.
What do you think about async calls ?

**Comment by Koromix** [comment]
I'm working on it :)

**Comment by Koromix** [comment]
It's not ready yet, and crashes easily, but the async branch is getting there :)

![image](https://user-images.githubusercontent.com/871846/168249601-9909b8e5-9264-4dff-ad31-9b6441e17f59.png)

**Comment by xan105** [comment]
Amazing 🎉
I'm glad you choose to use `fn.async()` like _ffi/ffi-napi_  👍

Keep up the good work.

<hr>

Appreciation note unrelated to the subject:

So far your lib has been a delight to use: fast, correctness, reliable.
Special mention when comparing to ref-napi (struct) which is a hassle with nested struct (offset etc).
Can't wait to have async and callback and ditch the _ffi-napi / ref-napi_ combo :D.
Will probably move all my modules using them to yours 😅

**Comment by Koromix** [comment]
Thank you, glad you like it!

My personal life is not at its highest point, this project and your appreciation are really helpful at the moment :)

**Comment by Koromix** [comment]
I've published 1.1.0-beta.1 with async support to NPM, with the beta tag 🙂 Install with:

```js
npm install koffi@beta
```

Example and documentation here: https://www.npmjs.com/package/koffi/v/1.1.0-beta.1#asynchronous-calls

**Comment by Koromix** [comment]
I'll add more tests before 1.1.0, to make sure everything works correctly...

... but other than that the feature seems to be done :) Feel free to reopen or open a new issue if you find a bug.

**Comment by Koromix** [comment]
> So far your lib has been a delight to use: fast, correctness, reliable. Special mention when comparing to ref-napi (struct) which is a hassle with nested struct (offset etc). Can't wait to have async and callback and ditch the _ffi-napi / ref-napi_ combo :D. Will probably move all my modules using them to yours 😅

Just in case, I've published Koffi 1.2.0-alpha.2 with callback support. It still needs heavy testing so I don't guarantee anything but you can try it you want. This release has not prebuilt binary.

```js
npm install koffi@alpha
```

Yeaah 🎉
