### ISSUE TITLE
koffi: wchar [Suggestion]

### ISSUE THREAD

**Issue by xan105** [Koromix/luigi#5]
`wchar_t` is widely used in the Windows API. About the only modern operating system to use it extensively is Windows _(sigh)_

> On platforms that support Unicode above the [basic multilingual plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane), wchar_t is usually 4 bytes (Linux, BSD, macOS).
> Only on Windows wchar_t is 2 bytes and encoded with UTF-16LE, due to [historical reasons](https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows) (Windows initially supported UCS2 only).

So ... here am I _again_ with a XInput example ahaha :)

`XINPUT_KEYSTROKE` has an `Unicode` property with `WCHAR`
cf: https://docs.microsoft.com/en-us/windows/win32/api/xinput/ns-xinput-xinput_keystroke

for `ref/ref-napi` I found these 2 packages back in the day:
- [ref-wchar](https://github.com/TooTallNate/ref-wchar)
- [ref-wchar-napi](https://github.com/Janealter/ref-wchar-napi)

I implemented neither in my XInput lib because they rely on `iconv` and I wasn't too keen on pulling `iconv` just for **this single** WCHAR.

I really like that koffi has types and struct built-in and you don't need to include ref-napi and cie.
Would implementing wchar be a difficult task ?
If it's too much trouble you can discard this suggestion. It just would be nice to have but that's about it.

**Comment by Koromix** [comment]
Is the WCHAR Unicode property used here? It's documented as unused.

Anyway, I've pushed some commits to add a few new types:
- string16, which is converted to UTF-16LE (which is what wchar_t is on Windows)
- char16 and char16_t for individual characters

Is that enough?
