### ISSUE TITLE
Prototype parser

### ISSUE THREAD

**Issue by pankerit** [Koromix/luigi#6]
classic function declaration works well but I am having trouble with the `Prototype parser`

code example
```js
const lib = koffi.load("user32");

const pos = koffi.struct("POINT", {
  x: "int",
  y: "int",
});

// const getCursorPos = lib.func("GetCursorPos", "bool", [
//   koffi.out(koffi.pointer(pos)),
// ]);

const getCursorPos = lib.func("bool GetCursorPos(POINT* lpPoint)");

setInterval(() => {
  const p = { x: 0, y: 0 };
  getCursorPos(p);
  console.log(p);
}, 100);
```

**Comment by Koromix** [comment]
Indeed, I need to document this better.
By default, pointer to objects are copied in but not out

To copy out, you can use :
* Classic declaration: koffi.out() for output parameters, or koffi.inout() for in and out parameters.
* Prototype parser: use the MSDN-like prefixes "_Out" or "_Inout_".

In your example that would be:

```c
const getCursorPos = lib.func("bool GetCursorPos(_Out_ POINT* lpPoint)")
```

**Comment by Koromix** [comment]
By using _Out_ or koffi.out, you can simplify the declaration of p with `const p = {}`.

It would not work with `koffi.in()` (the default) or `koffi.inout()`, because Koffi will complain about missing fields), but of output-only parameters it works just fine.
