### ISSUE TITLE
How to get a size of a type|struct?

### ISSUE THREAD

**Issue by pankerit** [Koromix/luigi#8]
Hi, in case you define a complex structure. 👍 

```js
const Image = koffi.struct('Image', {
    data: koffi.pointer('void'),
    width: 'int',
    height: 'int',
    mipmaps: 'int',
    format: 'int'
});

const GlyphInfo = koffi.struct('GlyphInfo', {
    value: 'int',
    offsetX: 'int',
    offsetY: 'int',
    advanceX: 'int',
    image: Image
});

koffi.sizeof(GlyphInfo)
koffi.sizeof(koffi.types.ulong)
```

**Comment by Koromix** [comment]
Just pushed a new beta (1.1.0-beta.4) with this in :) Install with:

```js
npm install koffi@beta
```

Documentation is here: https://www.npmjs.com/package/koffi/v/1.1.0-beta.4#type-information

**Comment by Koromix** [comment]
There's a typo, it's `koffi.alignof()`, not `koffi.alignon()`... :p

**Comment by Koromix** [comment]
It's published and out of beta, so `npm install koffi` 🙂 (the beta tag is gone)
